### ISSUE TITLE
Implement onDestroy/onStart operation

### ISSUE THREAD

**Issue by pointybeard** [tredly/tredly#14]
Currently we only have onCreate and onStop. Need to implement the onDestroy and onStart operation block to allow tasks to be completed at the point a container is destroyed/started.

**Comment by laurieodgers** [comment]
Currently the onCreate= commands are run on container start.

There will need to be some sort of "firstboot" flag to indicate to the container that the onCreate= commands need to be run since they must be run on a container that has been started.

**Comment by laurieodgers** [comment]
The aforementioned "firstboot" flag has been implemented but ondestroy onstart commands are yet to be implemented.

**Comment by laurieodgers** [comment]
Onstart, ondestroy has been implemented in https://github.com/vuid-com/tredly repo

**Comment by laurieodgers** [comment]
Complete in v1.1.0
