### ISSUE TITLE
Ports doesnt get forwarded

### ISSUE THREAD

**Issue by pointybeard** [tredly/tredly#36]
**This issue has been moved here from <https://github.com/tredly/tredly-host/issues/47>. Original issue submitted by dinapappor. Please see the original thread for more details but continue discussion here.**

----

While the reverse proxy feature with nginx works great I am having troubles getting regular destination nat to work.

I can see that in the container the ports get's added without a problem, it's added 3 times (port 13222) for three different tables, but I can't find the tables defined anywhere.

```
0100 allow log tcp from table(2) to 10.99.219.69 dst-port 13222 in via vnet0 setup keep-state
00200 allow log tcp from table(3) to 10.99.219.69 dst-port 13222 in via vnet0 setup keep-state
00300 allow log tcp from table(1) to 10.99.219.69 dst-port 13222 in via vnet0 setup keep-state
00400 allow log tcp from 10.99.219.69 to any dst-port 80 out via vnet0 setup keep-state
00500 allow log tcp from 10.99.219.69 to any dst-port 443 out via vnet0 setup keep-state
00600 allow log udp from 10.99.219.69 to any dst-port 53 out via vnet0 keep-state
00700 allow log tcp from 10.99.219.69 to any dst-port 80,5672 out via vnet0 setup keep-state
00800 allow log udp from 10.99.219.69 to any dst-port 53 out via vnet0 keep-state
00900 allow log udp from 10.99.219.69 to 10.99.255.254 dst-port 53 out via vnet0 keep-state
01000 allow log udp from 10.99.219.69 to 10.99.219.69 via vnet0 keep-state
01100 allow log tcp from 10.99.219.69 to 10.99.219.69 via vnet0 setup keep-state
01200 allow log ip from any to any via lo0
65535 deny ip from any to any
```
These rules are not in /usr/local/etc/ipfw.rules in the container. There's just a bash shebang in there.

On the tredly-host I am seeing no mention of port 13222. I've examined the `ipfw list` command as well as all the ipfw.* files.

From inside the container I can reach the service (in this case ssh) with that port without a problem.
Trying to reach the container from the tredly-host with `ssh -luser -p13222 containerip` fails with a timeout. And the same happens from the outside. 

SSH listening on port 13222 inside the container:

```
root@project-microservice:/ # netstat -an
netstat: kvm not available: /dev/mem: No such file or directory
Active Internet connections (including servers)
Proto Recv-Q Send-Q Local Address          Foreign Address        (state)
tcp4       0      0 *.13222                *.*                    LISTEN
tcp6       0      0 *.13222                *.*                    LISTEN
```

I have the following ports defined in the Tredlyfile:

```
# The following is for SSH into this instance to allow for ansible to ssh into this container and do hot code reloads.
tcpInPort=13222

# Needed to install packages
tcpOutPort=80

# Needed for connections to RabbitMQ
tcpOutPort=5672

# Needed for DNS queries.
udpOutPort=53
```

I am running my own package repo and I wont need https and ftp outbound. The packages get's installed fine.

I am also seeing that TSO doesn't get shut off by default. I think the issue is that since `net.inet.tcp.tso` is a read/write tunable it needs to go into /etc/sysctl.conf or else it wont get honored.

Loader tunables (The ones that can only be set at boot) goes into /boot/loader.conf and read/write tunables (the ones that can be changed anytime) goes into /etc/sysctl.conf.

If I can provide more information in order to debug these problems let me know. I would be happy to help.

**Comment by laurieodgers** [comment]
Closing this issue as it is resolved in v1.0
