### ISSUE TITLE
Standardise API config commands

### ISSUE THREAD

**Issue by pointybeard** [tredly/tredly#37]
**This issue has been moved here from <https://github.com/tredly/tredly-host/issues/43>. Please see the original thread for more details but continue discussion here.**

----

The following commands need to be changed from:
tredly-host config firewall addAPIwhitelist 
tredly-host config firewall clearAPIwhitelist

To:
tredly config api whitelist 
tredly config api whitelist clear

**Comment by laurieodgers** [comment]
Complete in v1.0
