### ISSUE TITLE
Allow MB of RAM/HDD

### ISSUE THREAD

**Issue by pointybeard** [tredly/tredly#38]
**This issue has been moved here from <https://github.com/tredly/tredly-host/issues/38>. Please see the original thread for more details but continue discussion here.**

----

I think that Tredly currently only allows a minimum of 1GB of RAM and 1GB of HDD. People should be able to set less than this.

**Comment by laurieodgers** [comment]
@pointybeard i believe this was implemented with 1.0 json schema?

**Comment by laurieodgers** [comment]
This has been implemented.
