### ISSUE TITLE
Tredly-host Layer7 Nginx Proxy Problems

### ISSUE THREAD

**Issue by pointybeard** [tredly/tredly#40]
**This issue has been moved here from<https://github.com/tredly/tredly-host/issues/29>. Original issue submitted by cmanns. Please see the original thread for more details but continue discussion here.**

----

Problem: After container-wordpress install css/js along with static images that are large (over 1KB it seems fail to load, and  max of 5KB seems to be delivered) incomplete chunked encoding error.

Reproduce Steps
Install Tredly-Host
Create tredly's example container-wordpress
Install said wordpress instance
Wordpress resources (CSS/JS along with images too large fail to load)

Using proxy_buffering off; seems to help the main wordpress load 99% correct, however no matter what I try wp-admin/ fails to load properly.

Only the below is in logs, using full error logging mode but this shows with default tredly error log setting if I recall. This has happened on a local install when tredly was first posted on reddit, and on a cloudsystem @cloudsigma I spun up few days ago to test 0.10.0

`016/05/11 10:37:11 [alert] 21928#0: *87 writev() failed (13: Permission denied) while sending to client, client: 68.189.105.204, server: vhost.domain.tld, request: "GET /wp-content/themes/twentysixteen/js/functions.js?ver=20160412 HTTP/1.1", upstream: "http://10.0.196.128:80/wp-content/themes/twentysixteen/js/functions.js?ver=20160412", host: "vhost.domain.tld", referrer: "http://vhost.domain.tld/"
2016/05/11 10:37:12 [alert] 21928#0: *90 writev() failed (13: Permission denied) while sending to client, client: 68.189.105.204, server: vhost.domain.tld, request: "GET /wp-includes/js/wp-emoji-release.min.js?ver=4.5.2 HTTP/1.1", upstream: "http://10.0.196.128:80/wp-includes/js/wp-emoji-release.min.js?ver=4.5.2", host: "vhost.domain.tld", referrer: "http://vhost.domain.tld/"`

**Comment by laurieodgers** [comment]
Closing this due to the time elapsed since first reported. If you are still having problems please open a new issue at https://github.com/tredly/tredly/issues
