### ISSUE TITLE
Tredly Host update command

### ISSUE THREAD

**Issue by pointybeard** [tredly/tredly#43]
**This issue has been moved here from<https://github.com/tredly/tredly-host/issues/17>. Please see the original thread for more details but continue discussion here.**

----

A command is required that updates all tredly components. A simple git pull/install is all that is required for this and could be incorporated within the installer file.

**Comment by laurieodgers** [comment]
The install.sh file will handle all installs/updates, however a check needs to be added to look for running containers. If containers are running then an error will be thrown.

**Comment by laurieodgers** [comment]
Aforementioned check has been added into the vuid-com integration branch and running the installer again appears to upgrade everything just fine. This will make it out with next release (1.1.0 or 1.0.3 if hotfixes are required)
