### ISSUE TITLE
Freebsd 10.3

### ISSUE THREAD

**Issue by cneira** [tredly/tredly#48]
Installation fails on FreeBSD 10.3 
### Tredly Command Center Installation complete. 
Success
Configuring Crontab
Success
Recompiling kernel as this kernel does not have VIMAGE built in
Cleaning previously compiled Kernel
Compiling kernel using 80% of available CPU resources (12 CPUs)
This may take some time...
1 error
Error: bash_install.sh: Failed to build kernel

==================================================
An error occurred during tredly-host installation.
==================================================

**Comment by laurieodgers** [comment]
Hi cneira
Thanks for the report. I have removed the offending line and a release will be made in the next few hours with this change.

**Comment by laurieodgers** [comment]
Hi Cneria, 1.0.2 has been pushed to master and fixes this issue - I will be closing this ticket but feel free to reply if you have any further problems.
