### ISSUE TITLE
Freebsd rc.conf is lost after reinstalling tredly

### ISSUE THREAD

**Issue by cneira** [tredly/tredly#49]
I tried to install tredly but if failed , but still overwrites rc.conf settings and saves them in rc.conf.old. the sad part is when installing again the original rc.conf is lost, which is a nasty bug. 
I think Tredly should create files using timestamps or uuid, so it is easier to go back and recover the overwritten values

**Comment by laurieodgers** [comment]
Thanks for the report. I will update all renamed files during install to include time since epoch instead of .old so that older files wont be deleted (eg. rc.conf.1466985691). Look for a release with this fix in the next few hours.

**Comment by laurieodgers** [comment]
Hi Cneria, 1.0.2 has been pushed to master and fixes this issue - I will be closing this ticket but feel free to reply if you have any further problems.
