### ISSUE TITLE
Tredly changes root password and set incorrect sysctl inet6 values 

### ISSUE THREAD

**Issue by cneira** [tredly/tredly#51]
Hi,
After rebooting my machine after failing to install Tredly, I could not logon remotely using ssh, so I had to go to the server console and find out that my root password did not work. It was changed to "tredly" , also error messages about incorrect sysctl inet6 values were outputted. I don't have the exact sysctl messages as the OS on machine has been reinstalled.
The issue happened in a fresh FreeBSD 10.3 installation.

**Comment by laurieodgers** [comment]
Hi Cneira
I have added the issue about root password change to #7 - essentially if installing from an ISO the root/tredly user will be set up, but if installing manually no user setup will happen.

With respect to sysctl.conf, we don't actually set any ipv6 specific values. Could it be the fact that your sysctl.conf has been moved by the tredly installer and thus /etc/sysctl.conf no longer holds values that FreeBSD is expecting?

**Comment by laurieodgers** [comment]
Hi @cneira we have just released tredly v1.1.0 which includes the user fixes. If installing from an ISO, the root user and tredly user will be set up. If doing a manual install (install BSD then git clone this repo) then user details will not be changed.

I haven't heard back from you regarding the ip6 issues, so I will be closing this ticket. Please create a new ticket (or re-open this one if you can) if you continue to experience problems.
