### ISSUE TITLE
Creating users

### ISSUE THREAD

**Issue by dinapappor** [tredly/tredly#9]
How does one create users for this?

I found no documentaion on how to do this.

The commands listed in tredly-cli repo does not work.

**Comment by laurieodgers** [comment]
Hi dinapappor, the commands listed in tredly-cli are to create users/admins for tredly-api access. Are you trying to create local (UNIX) users?

**Comment by laurieodgers** [comment]
Hi Dinapappor. It appears this is no longer an issue so I will be closing this ticket. if you are still having problems please reply to this ticket or open a new one.
