### ISSUE TITLE
Does file/folder mapping in tredlyfile file allow rename

### ISSUE THREAD

**Issue by nathanaherne** [tredly/tredly#95]
for instance can you do fileFolderMapping= /nginx/nginx.conf /usr/local/etc/nginx/blah.ha?

If not, can we add this functionality please?

**Comment by laurieodgers** [comment]
Yes this does work for both individual files and folders, both from container source directory and partition source directory.

I have tested with the following yaml:
        -
          type: "fileFolderMapping"
          source: "/test.conf"
          target: "/newfile.conf"
        -
          type: "fileFolderMapping"
          source: "/test"
          target: "/newfolder"
        -
          target: "/frompartition"
          type: "fileFolderMapping"
          source: "/testfolder/"
