### ISSUE TITLE
Destroying partition does not destroy its directory

### ISSUE THREAD

**Issue by nathanaherne** [tredly/tredly#98]
If you create a partition "Testing" and then destroy it, the directory /tredly/ptn/Testing is not destroyed and it should be. Tredly version - tredly 1.1.7 (built: August 2 2016)

**Comment by laurieodgers** [comment]
Closing this as it is a duplicate of https://github.com/tredly/tredly/issues/82 . The code for this is in vuid-com's integration branch and will make it out with next release (likely 1.1.8)
